[[var]]
identifier = "class_name"
message = "How would you like to name your class?"

[[var]]
identifier = "namespace"
help_message = "Namespaces are used to group related classes and prevent naming conflicts."

